name: Run Ansible on EC2
on:
  workflow_dispatch:

jobs:
  ansible_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Add EC2 host key to known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H 43.207.87.237 >> $HOME/.ssh/known_hosts
       
      - name: Run Ansible Playbook
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          ansible-playbook \
            -i "43.207.87.237," \
            -u ec2-user \
            --private-key key.pem \
            Ansible/playbook.yml
