name: Terraform CI

on:
  pull_request:
    paths:
     - 'terraform/**/*.tf'
     - 'terraform/**.tftest.hcl'
     - '.github/workflows/*.yaml'
  
  push:
    branches:
      - main
    paths:
     - 'terraform/**/*.tf'
     - 'terraform/**.tftest.hcl'
     - '.github/workflows/*.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DB_PASSWORD          : ${{ secrets.DB_PASSWORD }}
      AWS_DEFAULT_REGION   : ap-northeast-1

    steps:
     - name: Checkout repository
       uses: actions/checkout@v5

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: '1.13.3' 

     - name: Terraform init
       run: terraform init
   
     - name: Terraform fmt
       run: terraform fmt -check

     - name: Terraform validate
       run: terraform validate
   
     - name: Run Terraform tests
       run: |
         terraform test \
           -var "db_password=${DB_PASSWORD}" \
           -var "vpc_id=vpc-dummy" \
           -var "public_subnet_id=subnet-dummy" \
           -var "key_name=my-keypair-dummy" \
           -var "my_ip=1.2.3.4/32"

     - name: Terraform plan
       if: github.event_name == 'pull_request'
       run: |
         terraform plan \
           -var "db_password=${DB_PASSWORD}" \
           -var "vpc_id=vpc-dummy" \
           -var "public_subnet_id=subnet-dummy" \
           -var "key_name=my-keypair-dummy" \
           -var "my_ip=1.2.3.4/32"

     - name: Terraform apply
       if: github.event_name == 'push'
       run: |
         terraform apply -auto-approve \
           -var "db_password=${DB_PASSWORD}" \
           -var "vpc_id=vpc-dummy" \
           -var "public_subnet_id=subnet-dummy" \
           -var "key_name=my-keypair-dummy" \
           -var "my_ip=1.2.3.4/32"

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true
