name: Terraform CI

on:
  pull_request:
    paths:
     - 'terraform/**/*.tf'
     - 'terraform/**.tftest.hcl'
     - '.github/workflows/*.yaml'
  
  push:
    branches:
      - main
    paths:
     - 'terraform/**/*.tf'
     - 'terraform/**.tftest.hcl'
     - '.github/workflows/*.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION   : ap-northeast-1

    defaults:
      run:
        working-directory: ./terraform

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: '1.13.3' 

     - name: Terraform init
       run: terraform init
   
     - name: Terraform fmt
       run: terraform fmt -check

     - name: Terraform validate
       run: terraform validate
   
     - name: Run Terraform tests
       run: terraform test

     - name: Terraform plan
       if: github.event_name == 'pull_request'
       run: terraform plan

     - name: Terraform apply
       if: github.event_name == 'push'
       run: terraform apply -auto-approve
